"""Adding the added_date field to the BookCopies table

Revision ID: 41f0c7ae44d3
Revises: a30cf82199db
Create Date: 2020-04-25 10:07:08.304894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f0c7ae44d3'
down_revision = 'a30cf82199db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_copies', sa.Column('added_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_copies', 'added_date')
    # ### end Alembic commands ###
