"""Added the issue_status column to BooksIssued

Revision ID: 56f9c9656a11
Revises: de7dc6e59bff
Create Date: 2020-04-27 19:19:34.233198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f9c9656a11'
down_revision = 'de7dc6e59bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_issued', sa.Column('issue_state', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_issued', 'issue_state')
    # ### end Alembic commands ###
