"""Adding a new issuer_name column to BooksIssued table

Revision ID: 95abfa8674ce
Revises: 8cd21f401329
Create Date: 2020-04-28 12:34:47.333886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95abfa8674ce'
down_revision = '8cd21f401329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_issued', sa.Column('issuer_name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_issued', 'issuer_name')
    # ### end Alembic commands ###
