"""Adding the BookCopies table

Revision ID: a30cf82199db
Revises: f38bcf81818f
Create Date: 2020-04-24 22:11:00.068618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30cf82199db'
down_revision = 'f38bcf81818f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_copies',
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_copy_id')
    )
    op.add_column('books', sa.Column('num_copies', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=False))
    op.drop_column('books', 'copies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('copies', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('books', 'pages')
    op.drop_column('books', 'num_copies')
    op.drop_table('book_copies')
    # ### end Alembic commands ###
