"""Adding roles to users

Revision ID: cf7004c91a37
Revises: 7f559cbdcc19
Create Date: 2020-04-21 17:22:30.961798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7004c91a37'
down_revision = '7f559cbdcc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###
