"""Removed the short description

Revision ID: f30b1c0ed26f
Revises: 4b6014ce6c09
Create Date: 2020-04-27 19:33:35.806494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30b1c0ed26f'
down_revision = '4b6014ce6c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
