"""Removing the Date of Issue column from booksissued table

Revision ID: f50465ab5cf1
Revises: 95abfa8674ce
Create Date: 2020-04-28 20:36:30.526500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50465ab5cf1'
down_revision = '95abfa8674ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_issued', 'issue_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_issued', sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
